# Name of the GitHub Actions workflow.
name: Deploy Jupyter Book to GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the "master" branch.
  push:
    branches:
      - master
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "deploy".
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installs uv. It will automatically detect and install the Python version
      # specified in the .python-version file.
      - name: Install uv and Python
        uses: yezz123/setup-uv@v4
        with:
          uv-version: '0.7.5'

      # 3. Installs the project dependencies from pyproject.toml using uv.
      - name: Install dependencies with uv
        run: uv sync
        
      # 4. Builds the Jupyter Book.
      # The "uv run" command executes the command within the managed environment.
      - name: Build the book
        run: uv run jupyter-book build modules

      # 4.1 mathjax
      - name: static mathjax
        run: uv run local_mathjax.py
      
      # 4.2 mermaid
      - name: static mermaid
        run: uv run local_mermaid.py

      # 5. Sets up the GitHub Pages artifact.
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Uploads the build output as a GitHub Pages artifact.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The folder to upload is the build output of Jupyter Book.
          path: ./modules/_build/html

      # 7. Deploys the artifact to GitHub Pages.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
